version: "3.8"

services:
  tony:
    build:
      context: .
    container_name: tony
    restart: unless-stopped
    ports:
      - "3101:80"
    network_mode: bridge
    environment:
      - TZ=Europe/London
      - GEMINI_API_KEY=${GEMINI_API_KEY}
